履歴画面の見た目のみ作成
masayatoida/ChildStock pull request #13
Opened 2022-01-09 00:58 UTC by masayatoida

## コマンド
git checkout -b feature/add-ui-history origin/feature/add-ui-history
※ 該当ブランチ名は各自変更してください
## 概要
・履歴画面の見た目（セル）のみ作成
## レビューで見て欲しいポイント(不安なところ)
特になし
## あれば参考URL
## セルフレビュー
レビュー依頼の前に確認をしてください:電球:
✅期待通りの挙動をするか?
✅タイポしていないか？
✅warningが新たに増えていないか？
✅リファクタリングできる余地がないか?
✅コンフリクトが発生してないか？
✅UIのレイアウトが崩れていないか？ ※UIを実装した場合のみでOK
すべて:チェックマーク_緑:をつけたら、レビューを依頼しましょう！:+1:
## 補足
## 環境
Xcode12.5.1

2022-01-09 05:06 UTC, fuchi0741 commented
@masayatoida 
(MUST)
画面遷移ができないとUIが確認できないため追加実装お願いしますー！
ダミーデータを入れてみて、実際の履歴画面UIが確認できるように実装お願いしますー！

2022-01-10 02:46 UTC, masayatoida commented
WIP:作業中ですがエラー解消できないため、ご確認お願いします！

2022-01-10 07:49 UTC, fuchi1234 commented
> @fuchi0741 WIP:作業中ですがエラー解消できないため、ご確認お願いします!

![スクリーンショット 2022-01-10 16 46 28](https://user-images.githubusercontent.com/97375744/148732872-9c0fcad8-1ad7-468a-855b-838eb28a7b1b.png)

2022-01-15 13:11 UTC, masayatoida commented
@fuchi0741 
履歴ボタンを押下すると遷移できるようになりました！！
ご確認お願いします。

2022-01-16 04:37 UTC, fuchi0741 requested changes
@masayatoida 
何件かコメントしました！
WANT: タイトルになんの画面がわかるような処理があるといいかなと思いました 💡

2022-01-16 04:37 UTC, fuchi0741 commented on ChildStock/Controller/History/HistoryViewController.swift
> +final class HistoryViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
MUST: プロトコルごとにextension作成したいです！

2022-01-16 04:37 UTC, fuchi0741 commented on ChildStock/Controller/Calculation/CalculationViewController.swift
> +        let historyVC = storyboard.instantiateViewController(withIdentifier: "History") as! HistoryViewController
must: as!はなるべく意識して使用しないようにしたいです 💡

2022-01-16 04:37 UTC, fuchi0741 commented on ChildStock.xcodeproj/project.pbxproj
> +		008AFA7B279296DB0087315A /* History.storyboard in Resources */ = {isa = PBXBuildFile; fileRef = 008AFA7A279296DB0087315A /* History.storyboard */; };
WANT: `History.storyboardrd`の命名ですが、対応する.swiftファイルと同じ命名にした方が後ほど管理がしやすそうです 💡

2022-01-16 04:49 UTC, fuchi0741 commented on ChildStock/Controller/Calculation/CalculationViewController.swift
> +final class CalculationViewController: UIViewController,HistoryButtonViewDelegate {
MUST: ここもextension分けたいです 💡

2022-01-16 14:27 UTC, masayatoida commented on ChildStock/Controller/Calculation/CalculationViewController.swift
> +        let historyVC = storyboard.instantiateViewController(withIdentifier: "History") as! HistoryViewController
@fuchi0741 
何度も勉強したはずが・・・
すみません修正します！

2022-01-16 14:45 UTC, masayatoida commented
@fuchi0741 
修正しました！ご確認お願いします！！

2022-01-17 01:01 UTC, fuchi0741 commented
@masayatoida 
> WANT: タイトルになんの画面がわかるような処理があるといいかなと思いました 💡
Q: こちらは一旦非対応ということで大丈夫でしょうか？

2022-01-17 13:22 UTC, masayatoida commented
@fuchi0741 

> WANT:タイトルになんの画面がわかるような処理があるといいかなと思いました 💡
すみません。タイトルとはどこのことでしょうか？

2022-01-19 15:23 UTC, fuchi0741 requested changes
@masayatoida 
追加でコメントしました！

2022-01-19 15:23 UTC, fuchi0741 commented on ChildStock/Controller/Calculation/CalculationViewController.swift
> +        let storyboard = UIStoryboard(name: "HistoryViewController", bundle: nil)
(MUST)リテラルを使用しているため、回避しましょう！

2022-01-25 04:14 UTC, fuchi0741 requested changes
@masayatoida 1点追加でコメントしました１

2022-01-25 04:14 UTC, fuchi0741 commented on ChildStock/Controller/Calculation/CalculationViewController.swift
> +        let historyVC = storyboard.instantiateViewController(withIdentifier: HistoryViewController.className) as! HistoryViewController
(MUST)as! がまだ残っていそうです 👀

2022-01-30 12:29 UTC, masayatoida commented on ChildStock/Controller/Calculation/CalculationViewController.swift
> +        let historyVC = storyboard.instantiateViewController(withIdentifier: HistoryViewController.className) as! HistoryViewController
対応しました！

2022-01-30 13:13 UTC, fuchi0741 requested changes
@masayatoida 
すいません！1点追加です！

2022-01-30 13:13 UTC, fuchi0741 commented on ChildStock/Controller/History/HistoryViewController.swift
> +        navigationBar.delegate = self
`navigationBar.delegate = self`
こちらですが、`setupTableView`メソッド内にあるのが違和感を感じるため、このメソッドに書かなくてもできるようにリファクタリングしたいです 🤔

2022-01-30 14:07 UTC, masayatoida commented on ChildStock/Controller/History/HistoryViewController.swift
> +        navigationBar.delegate = self
再度リファクタリングしました！！

2022-01-30 14:11 UTC, fuchi0741 approved these changes
LGTM 🙆‍♂️

2022-01-30 14:12 UTC, fuchi0741 commented
みました！マージします！

2022-01-30 14:12 UTC, merged