計算画面の見た目全体を作成
masayatoida/ChildStock pull request #9
Opened 2021-12-30 11:40 UTC by masayatoida

@fuchi0741
計算画面の見た目を作成しました。
・毎月のお小遣いと株を買う期間、合計額は1つのviewにテキストフィールドとラベルを設置
・計算するボタンと履歴を見るボタンはそれぞれviewの上にそれぞれボタンを設置
・Outlet接続とAction接続を行なった
・CustomViewに必要なコードのみ実装済み

以上です。よろしくお願いします。

2021-12-31 04:58 UTC, fuchi0741 commented
@masayatoida 
MUST:  
ファイルを追加したときにでてくる`ChildStock.xcodeproj/project.pbxproj`が差分してなさそうなので確認と修正お願いします！
何か削除したなどの心あたりはありますか？

自分のローカル環境で仮にファイルを新規作成すると、`ChildStock.xcodeproj/project.pbxproj`の差分が確認できました。

2021-12-31 05:03 UTC, fuchi0741 requested changes
@masayatoida 
いくつかコメントしました！

2021-12-31 05:03 UTC, fuchi0741 commented on ChildStock/CalculationButtonView.swift
> +class CalculationButtonView: UIView {
WANT: 
どんな意図で追加したかがわかりずらいため、今後どんな実装をする予定かをTODOコメントを書いてもらえるとわかりやすいです！

ex) TODO: 〇〇画面の〇〇Viewを後続タスクにて実装予定

2021-12-31 05:03 UTC, fuchi0741 commented on ChildStock/CalculationButtonView.swift
> +
WANT: この時点で削除できるコメントは削除お願いします！

2021-12-31 05:03 UTC, fuchi0741 commented on ChildStock/CalculationButtonView.swift
> +class CalculationButtonView: UIView {
WANT: この時点でfanalキーワードかけると思うため記載お願いします！

2021-12-31 05:03 UTC, fuchi0741 commented on ChildStock/CalculationViewController.swift
> +    @IBOutlet weak var calculationButtonView: CalculationButtonView!
WANT: privateが欲しいです！

2021-12-31 05:03 UTC, fuchi0741 commented on ChildStock/CalculationViewController.swift
> +    @IBOutlet weak var InputTextView: InputTextView!
MUST: outlet接続は変数と同じ命名規則のため、
先頭は小文字でお願いします！

ex) HistoryButtonView → historyButtonView

2021-12-31 05:05 UTC, fuchi0741 commented
@masayatoida 
MUST: このPRに対応するissueを`Linked issues`から紐付けをお願いします！

2021-12-31 17:01 UTC, masayatoida commented on ChildStock/CalculationButtonView.swift
> +class CalculationButtonView: UIView {
了解しました！

2021-12-31 17:02 UTC, masayatoida commented on ChildStock/CalculationViewController.swift
> +    @IBOutlet weak var InputTextView: InputTextView!
文言修正し、元の接続は切ってから再接続しました。

2021-12-31 17:03 UTC, masayatoida commented
> @masayatoida MUST: このPRに対応するissueを`Linked issues`から紐付けをお願いします！

紐付けしました！

2021-12-31 17:04 UTC, masayatoida commented
> @masayatoida MUST: ファイルを追加したときにでてくる`ChildStock.xcodeproj/project.pbxproj`が差分してなさそうなので確認と修正お願いします！ 何か削除したなどの心あたりはありますか？
> 
> 自分のローカル環境で仮にファイルを新規作成すると、`ChildStock.xcodeproj/project.pbxproj`の差分が確認できました。
> 
> ここの修正が範囲としてないと、マージできないです😓

2021-12-31 17:11 UTC, masayatoida commented
修正いたしました。再度ご確認お願いします！！

2021-12-31 17:43 UTC, fuchi0741 requested changes
@masayatoida 
commitの粒度いい感じです！
あとUI実装もGOODですね！！！

WANT: このタイミングでMVCなどフォルダ作ってもいいかもです。

WANT: 次からカンバンのチケットをレビュー依頼のところへ移動をお願いします！

2021-12-31 17:43 UTC, fuchi0741 commented on ChildStock/CalculationViewController.swift
> +    override func viewDidLoad() {
WANT: outlet接続とライフサイクルメソッドは間1行スペースが欲しいですmm

2021-12-31 17:43 UTC, fuchi0741 commented on ChildStock/HistoryButtonView.swift
> +    @IBAction private func didTapHistoryButton(_ sender: UIButton) {
WANT: メソッドとメソッドの間は1行開けたいです！

2021-12-31 17:43 UTC, fuchi0741 commented on ChildStock/HistoryButtonView.swift
> +
ここは不要なスペースなので削除したいです！

2021-12-31 17:43 UTC, fuchi0741 commented on ChildStock/Base.lproj/Main.storyboard
> +                                <color key="backgroundColor" systemColor="systemGreenColor"/>
WANT: バックグラウンドカラーはうすいグレーで統一したいですmm

2021-12-31 17:59 UTC, fuchi0741 commented
@masayatoida 

MUST: 1点惜しい点が！！4インチで見るとレイアウトが崩れてしますようです。
ご確認お願いします！(PCの調子が悪くスクショの共有ができないmm)

AutoLayoutに改善の余地がありそうです！
まあ一旦4インチでもレイアウトが崩れてないように修正するチケットを新しく作って別途対応でいいかと思いますが、いかがでしょうか？
修正内容はMUSTですが、タイミングはWANTなので戸井田さんにお任せします。

2022-01-01 13:26 UTC, masayatoida commented
@fuchi0741 
4インチでもレイアウトが崩れてないように修正するチケットを新しく作って別途対応します！

2022-01-01 13:58 UTC, masayatoida commented
@fuchi0741
修正いたしました。再度ご確認お願いします！！

2022-01-01 14:19 UTC, fuchi0741 commented
@masayatoida WANT
フォルダは次commitでも良かったかもですね！

2022-01-01 14:19 UTC, fuchi0741 commented
マージします！

2022-01-01 14:19 UTC, merged